### ISSUE TITLE
Facing a run time error while executing TestNG.xml

### ISSUE THREAD

**Issue by jsindhukilari** [tabhresh/Edureka_27Aug#5]
Facing the folllowing run time error while executing TestNG.xml with option "Run as TestNG Suite"
RemoteTestNG] detected TestNG version 6.14.2
java.lang.NullPointerException
	at org.testng.internal.MethodHelper.findDependedUponMethods(MethodHelper.java:94)
	at org.testng.internal.MethodHelper.topologicalSort(MethodHelper.java:241)
	at org.testng.internal.MethodHelper.sortMethods(MethodHelper.java:317)
	at org.testng.internal.MethodHelper.collectAndOrderMethods(MethodHelper.java:64)
	at org.testng.internal.TestNGMethodFinder.findConfiguration(TestNGMethodFinder.java:197)
	at org.testng.internal.TestNGMethodFinder.getAfterTestConfigurationMethods(TestNGMethodFinder.java:93)
	at org.testng.TestClass.initMethods(TestClass.java:135)
	at org.testng.TestClass.init(TestClass.java:74)
	at org.testng.TestClass.<init>(TestClass.java:38)
	at org.testng.TestRunner.initMethods(TestRunner.java:389)
	at org.testng.TestRunner.init(TestRunner.java:271)
	at org.testng.TestRunner.init(TestRunner.java:241)
	at org.testng.TestRunner.<init>(TestRunner.java:192)
	at org.testng.remote.support.RemoteTestNG6_12$1.newTestRunner(RemoteTestNG6_12.java:33)
	at org.testng.remote.support.RemoteTestNG6_12$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG6_12.java:66)
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:713)
	at org.testng.SuiteRunner.init(SuiteRunner.java:260)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:198)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1295)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1273)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1128)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by Mundepi28** [comment]
Hi,

Looking at this, can't say the actual problem, but maybe you can try few things:
1.  try with TEST NG version 6.11, this worked for me.
2. Error says null pointer exception, so seems to me that you have not initialized some variable maybe. Check through the code that you have initialised all the variables and commands properly.

If possible, please share your code and test scripts so that I can also have a look to understand the problem.

Regards
Prashant

**Comment by jsindhukilari** [comment]
Thanks Prashant! There was some problem with WebDriver variable initialization. Now its working.

**Comment by Mundepi28** [comment]
Great, great!
